### ISSUE TITLE
Store all the recipients

### ISSUE THREAD

**Issue by jbinary** [Incred/mailkeeper#2]
Problem: currently postfix sends a message for each message being sent and for _each recipient_ as well. But we always only store the first recipient which makes and then if bounce happens, all the copies are being marked as bounced which spoils deliverability stats.

Solution: it's a tough one. All solutions I can think of have some disadvantages.

It seems we still have to make a record for each recipient but maybe split them between the tables, so we don't have to duplicate all the content each time?

Then if we receive a bounce we can only update one of the entries' statuses by using both Message-ID and recipient?

Has direct relation to #1 too.

**Comment by Incred** [comment]
To save recipient address correctly, we'll use X-Original-To header (set by postfix) fa8caf428ce49fd3ad5f6eab1774aa7242c9b911

**Comment by jbinary** [comment]
So this one can be closed, right?

**Comment by Incred** [comment]
Yes
